[build]
  # Directorio base del proyecto
  base = "."
  
  # Comando de construcción
  command = "npm run build"
  
  # Directorio de salida para Next.js
  publish = "out"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"

# Redirecciones para Next.js (comentadas - Next.js maneja sus propias rutas)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para archivos de imagen
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuración de funciones serverless (comentada - no se usan)
# [functions]
#   directory = "netlify/functions"

# Configuración de plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración de formularios (si se usan)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Configuración de deploy
[build.processing.images]
  compress = true
