module.exports = {
  theme: {
    extend: {
      colors: {
        'background': 'rgb(var(--background))',
        'foreground': 'rgb(var(--foreground))',
        'card': 'rgb(var(--card))',
        'card-foreground': 'rgb(var(--card-foreground))',
        'primary': 'rgb(var(--primary))',
        'primary-foreground': 'rgb(var(--primary-foreground))',
        'primary-hover': 'rgb(var(--primary-hover))',
        'secondary': 'rgb(var(--secondary))',
        'secondary-foreground': 'rgb(var(--secondary-foreground))',
        'muted': 'rgb(var(--muted))',
        'muted-foreground': 'rgb(var(--muted-foreground))',
        'destructive': 'rgb(var(--destructive))',
        'destructive-foreground': 'rgb(var(--destructive-foreground))',
        'destructive-hover': 'rgb(var(--destructive-hover))',
        'success': 'rgb(var(--success))',
        'success-foreground': 'rgb(var(--success-foreground))',
        'warning': 'rgb(var(--warning))',
        'warning-foreground': 'rgb(var(--warning-foreground))',
        'info': 'rgb(var(--info))',
        'info-foreground': 'rgb(var(--info-foreground))',
        'input': 'rgb(var(--input))',
        'input-solid': 'rgb(var(--input-solid))',
        'border': 'rgb(var(--border))',
        'ring': 'rgb(var(--ring))',
        'popover': 'rgb(var(--popover))',
        'popover-foreground': 'rgb(var(--popover-foreground))',
        'accent': 'rgb(var(--accent))',
        'accent-foreground': 'rgb(var(--accent-foreground))',
        'title': 'rgb(var(--title))',
        'title-foreground': 'rgb(var(--title-foreground))',
      },
    },
  },
};
